### PR TITLE
Correctly name podspec file

### LINKED ISSUE #229: Podspec file not being named correctly in certain builder bob configurations
After setting everything up according to the step by step guide, the header file `UniffiCallInvoker.h` cannot be found while building for iOS:

`#include "UniffiCallInvoker.h"`

The include happens in the the file `cpp/generated/foobar.hpp`

Is there anything I am doing wrong?

Maybe the include path is not set correctly for the Xcode project?

Thanks!

### PR DESCRIPTION
**Pull request by jhugman**
Fixes #229 .

This PR changes the name of the podspec file to camel case from kebab case.

It also adds some testing infrastructure to ensure it's tested on CI.

### CODE REVIEW

**Comment by Johennes** [comment]
Sorry for the delay. The built has since been fixed with the RN update itself. Do we still need this?

**Comment by jhugman** [comment]
Hi @Johennes , I re-phrased the PR to be a fix for the podspec rename file. Would you mind taking a look when you have a minute?

File: scripts/test-turbo-modules.sh [hunk 1]
```diff
@@ -26,7 +26,7 @@ usage() {
   echo "  -A, --android                      Build for Android."
   echo "  -I, --ios                          Build for iOS."
   echo "  -C, --ubrn-config                  Use a ubrn config file."
-  echo "  -P, --packgage-json-mixin          Merge another JSON file into package.json"
+  echo "  -P, --package-json-mixin          Merge another JSON file into package.json"
```
Comment (Johennes) [inline scripts/test-turbo-modules.sh:29]:
```suggestion
  echo "  -P, --package-json-mixin           Merge another JSON file into package.json"
```

Sorry, I think I have some obsessive compulsive disorder when it comes to alignment. :sweat_smile:

File: scripts/test-turbo-modules.sh [hunk 2]
```diff
@@ -269,10 +298,11 @@ check_lines() {
...
   check_line_unchanged "./android/cpp-adapter.cpp" "::multiply"
 
-  check_line_unchanged "./ios/*.h" "#import"
-  check_line_unchanged "./ios/*.h" "Spec.h"
+  # check_line_unchanged "./ios/*.h" "#import"
+  # check_line_unchanged "./ios/*.h" "Spec.h"
+  check_line_unchanged "./ios/*.h" "Spec>"
   check_line_unchanged "./ios/*.h" "<Native"
-  check_line_unchanged "./ios/*.h" "<RCTBridgeModule"
+  # check_line_unchanged "./ios/*.h" "<RCTBridgeModule"
```
Comment (Johennes) [inline scripts/test-turbo-modules.sh:305]: If we're planning to uncomment these again later, a comment explaining why they're currently commented might help. Otherwise, I guess we could also just delete them?
